### ISSUE TITLE
QGIS: Implement new Collection support

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-qgis#117]
- [x] Ensure we can receive commits with new collection structure
- [x] Ensure backwards compatibility (We can receive older commits with non-collection structure)
- [x] Send `Collection` structure from QGIS
- [ ] Move GIS Layers over to SpecklePY?
 
see https://github.com/specklesystems/speckle-sharp/issues/2187

**Comment by KatKatKateryna** [comment]
Must be synchronized with Collection implementation in specklepy

**Comment by KatKatKateryna** [comment]
Last point moved to https://github.com/specklesystems/specklepy/issues/274
