### ISSUE TITLE
Align project origin with non-GIS commits

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/speckle-qgis#166]
On receive in QGIS:
- identify Base Point or other origin points if available, and interpret it in QGIS in order to find appropriate CRS and add offsets/rotation if needed

**Comment by KatKatKateryna** [comment]
Discussion: https://www.notion.so/speckle/Alignment-of-coordinates-between-software-41640f53ec134c58b97a04bd08721e0e

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
