### ISSUE TITLE
GIS <> Revit better interop

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-qgis#167]
Currently, GIS objects in Revit are received as DirectShapes with a "Geberic Model" category, we should make sure they are sent with the right object model and inheritance so they get in Revit with the correct categorization.

**Comment by KatKatKateryna** [comment]
C# PR: https://github.com/specklesystems/speckle-sharp/pull/2867
Notes: https://www.notion.so/speckle/Revit-receiving-custom-properties-ed8685a108894275af6f0ebb38250c96

**Comment by KatKatKateryna** [comment]
TODO:
- convert more categories in Revit (e.g. Topography)

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-sharp/pull/2875
