### ISSUE TITLE
Add alignment conversions

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-qgis#23]
Add alignment to native conversion method for qgis

Mentioned in: https://speckle.community/t/qgis-connector-wip/1619/48?u=clrkng

**Comment by clairekuang** [comment]
Took a quick look at this and an `AlignmentToNative` method depends on 2 things to be implemented first:
- `ArcToNative` in QGIS: @KatKatKateryna @AlanRynne are arcs supported natively?
- `BuiltElements` classes in specklepy: @izzylys what's the status on adding builtelements in py? Could we create a temporary class for alignments specifically in QGIS until a proper builtelements implementation is done?

**Comment by AlanRynne** [comment]
Hmm... not sure if `arcs` really exist in QGIS, it may allow you to create them but end up being a polyline. I've done some googling but haven't found anything meaningful.

Good news is that we could just default to the `displayValue` of the arc and call it a day.
As for the `Alignment` class, i'm sure we could make a quick patch if the class implementation takes more than we want. 👍🏻

**Comment by clairekuang** [comment]
> Good news is that we could just default to the `displayValue` of the arc and call it a day.

Unfortunately arcs aren't inheriting from `IDisplayValue`, and most of the converters in sharp aren't sending them with display values afaik

**Comment by KatKatKateryna** [comment]
Arcs will be substituted with QgsCircularString in a new release👌
