### ISSUE TITLE
Refactor UI code out of `speckle_qgis.py` and into it's respective UI classes

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-qgis#33]
`speckle_qgis.py` is currently in charge of doing too many things, making it tricky to edit without introducing new bugs in the process.

Most of this code is UI based (callbacks for clicks, redrawing logic, etc), which should actually live inside it's own python classes.

These already exist but we were just using them as "dumb" wrappers for the UI file. Making them "smarter" would greatly simplify the code in the main plugin file.

**Comment by KatKatKateryna** [comment]
@AlanRynne please let me know if this is close: https://github.com/specklesystems/speckle-qgis/tree/release_2.8

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-qgis/pull/46
