### ISSUE TITLE
SpeckleException > UI & Exeption  

### ISSUE THREAD

**Issue by GianClaudioScarafini** [specklesystems/speckle-qgis#36]
HI,
First, thank you for your effort to make this happen! 

I have just taken a test that returns an error.

I am not sure that is the error; I have little knowledge of the nitty-gritty of the tool, and I am a beginner at coding...
I assume that the issue is related exception log to the function that is connected to the User interface. 

Or am I doing something wrong? 
 

```
2022-07-17T12:16:01     WARNING    Traceback (most recent call last):
              File "C:\Users\****\AppData\Roaming\Python\Python39\site-packages\specklepy\api\client.py", line 86, in __init__
              raise serverInfo
             specklepy.logging.exceptions.SpeckleException: SpeckleException: Failed to execute the GraphQL server request. Inner exception: __init__() got an unexpected keyword argument 'allowed_methods'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users\****\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\ui\add_stream_modal.py", line 67, in onAccountSelected
              self.speckle_client = SpeckleClient(account.serverInfo.url, account.serverInfo.url.startswith("https"))
              File "C:\Users\****\AppData\Roaming\Python\Python39\site-packages\specklepy\api\client.py", line 90, in __init__
              raise SpeckleException(f"{self.url} is not a compatible Speckle Server", ex)
             specklepy.logging.exceptions.SpeckleException: SpeckleException: https://speckle.xyz is not a compatible Speckle Server
```

Thank you

**Comment by AlanRynne** [comment]
Oh this is weird! the "is not a compatible speckle server" error should only happen with non-speckle servers. But that server url is correct so I'm not sure right now what could be happening there.

Me or @KatKatKateryna will try to have a look at it today. Hopefully its an easy fix :)

**Comment by KatKatKateryna** [comment]
Hi @GianClaudioScarafini , thanks for reporting this! Sometimes this exception shows up if there are some internet connection issues and Speckle cannot establish connection with the server. At what step are you getting this error? Did you set up your account successfully in Desktop SpeckleManager?

**Comment by KatKatKateryna** [comment]
Awesome! Will close the issue for now, feel free to report anything else that doesn't function a expected here, or in the [community forum](https://speckle.community/)
