### ISSUE TITLE
Issue when loading speckle plugin in QGIS

### ISSUE THREAD

**Issue by AdrianChrapliwy** [specklesystems/speckle-qgis#45]
I keep getting this issue when loading the Speckle Component in QGIS

Couldn't load plugin 'speckle-qgis' due to an error when calling its classFactory() method 

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.2-Buenos Aires Buenos Aires, feec3d3b12f

**Comment by KatKatKateryna** [comment]
Hi @AdrianChrapliwy ! Thanks for reporting this. Are you using the latest version of the plugin? May I ask you to copy as well the full Python Error Log accompanying the issue you described?

**Comment by AdrianChrapliwy** [comment]
hi, thank you for the quick response. I did use the last version, but I restarted qgis a few times and now it works.
