### ISSUE TITLE
Option to indicate a layer geometry type in UI

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/speckle-qgis#47]

**Comment by jsdbroughton** [comment]
Example use case. Where a geopackage set of layers share the layer name but are differentiated (point/linestring/multipoly etc)

The layers list is currently in the same order as the QGIS Layers panel, but the ability select layer and geometype would be beneficial

![Screenshot 2022-10-13 at 14 50 45](https://user-images.githubusercontent.com/760691/195615671-35d2a5e7-c37b-4f6e-ae72-ad3ab07fc3bd.png)  vs  ![Screenshot 2022-10-13 at 14 50 56](https://user-images.githubusercontent.com/760691/195615696-557d18a6-e45e-4a8b-aef2-7c5f59ef0591.png)

**Comment by KatKatKateryna** [comment]
included in 2.12 UI
