### ISSUE TITLE
Account Selection dropdown should include account email in addition to name

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-qgis#52]
Usecase:

Where a user has multiple accounts on a server all using their same proper name, having sight of the email used for each account would enable users to determine the correct account to use correctly

![Screenshot 2022-10-13 at 12 33 12](https://user-images.githubusercontent.com/760691/195616955-d4e066aa-8247-4285-9dfc-81410e2ddb4c.png)

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-qgis/commit/f7e9457246ec067bc9651ed4a5f8fe06ab4df4fb

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-qgis/commit/f7e9457246ec067bc9651ed4a5f8fe06ab4df4fb
