### ISSUE TITLE
Feature: Ability to create streams and branches with the UI

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-qgis#55]
This would bring feature parity with other connectors. 

The current method is to create streams or branches at the server (or with other connectors) and refresh the QGIS Ui to make these visible.

The add stream button is ambiguous. + means `Select` for the current project and not `Create Stream`.

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-qgis/commit/1bde6f5965811c6e87e2ac67bff8943e044a90ef
