### ISSUE TITLE
Adding Public streams by URL only matches where the active account is for the same server

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-qgis#57]
Following the implementation of https://github.com/specklesystems/speckle-qgis/issues/56.

Should the current account server be relevant for accessing from a public stream?

Perhaps the Search should use the StreamWrapper rather than the client: transport? 

I can self-assign this and check it out.

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-qgis/commit/a25ca6457c09f25706a5e706464734050df74fd3
