### ISSUE TITLE
Release 2.9.0 doesn't work 

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-qgis#62]
The release in the QGIS Plugin repository will not load. The matched release 2.9.0 here also will not load, as reported on the forum. 

https://speckle.community/t/unable-to-load-the-speckle-plugin-on-qgis-for-mac/3922/7

Installing as I did for testing as a clone of the latest does work. Although the user who reported the error found that it did not.

Something odd seems to happen in the process of zip/unzip - I need to test this further.

**Comment by KatKatKateryna** [comment]
_init_ file turned out empty in the released 2.9.0, pushed the quick fix as 2.9.4. Will close this when plugin is approved for Marketplace and tested
