### ISSUE TITLE
Assign proper min-max to raster renderers upon receiving

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/speckle-qgis#81]
E.g. receiving this applies wrong range: https://speckle.xyz/streams/df48a54b8e/commits/4cf434f0b9

**Comment by KatKatKateryna** [comment]
Raster layer after applying StretchToMinMax contrast enhancement algorithm: 
![raster_error_01](https://github.com/specklesystems/speckle-qgis/assets/89912278/39d5c574-e5b9-4420-ab65-78f11236ae70)

Overall range of colors is preserved, but intermediate shades are lost. Solved by manually opening layer properties and clicking Apply, but not programmatically (.e.g. .triggerRepaint() or iface refresh ): 
![raster_error_02](https://github.com/specklesystems/speckle-qgis/assets/89912278/ae456860-1457-4bba-8ea3-e8c5cf5f9d58)

![raster_error_03](https://github.com/specklesystems/speckle-qgis/assets/89912278/034365f7-9802-4115-a65e-209ceba1bb75)

Thread found from 3 years ago on gis.stackexhange, with no updates since:
![raster_error_04](https://github.com/specklesystems/speckle-qgis/assets/89912278/7fae19cc-3f60-480d-9671-ba799b43f7e7)

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
